# Partie 1

# Nom et Prénoms : N'DRI KOFFI Pierre Ezéchiel

#### Exercice 1 - Manipulations de vecteurs

On donne :
$$
u1 = 
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}

u2 = 
\begin{bmatrix}
-5 \\
2 \\
1
\end{bmatrix}

u3 = 
\begin{bmatrix}
-1 \\
-3 \\
7
\end{bmatrix}
$$

1. Définir ces vecteur.
2. Calculer u<sub>1</sub> + u<sub>2</sub>,u<sub>1</sub> + 3u<sub>2</sub> − 5u<sub>3</sub>,u<sub>3</sub>/5
3. Calculer le produit des compansantes des vecteur u<sub>1</sub> et u<sub>2</sub>, terme à terme.
4. Calculer les produits u<sup>T</sup><sub>1</sub> u<sub>2</sub> et u<sub>1</sub> u<sup>T</sup><sub>2</sub>.
5. Crée par concaténation la matrice :
$$
\begin{bmatrix}
1 & -5 &-1 \\
2 & 2 &-3 \\
3 & 1 & 7
\end{bmatrix}
$$


1. Définissons ces vecteurs:

In [1]:
#importons la bibliothèque qui nous permettra de créer ces vecteurs et de travailler sur eux
import numpy as np
#Définissons les vecteurs
u1 = np.array([1,2,3])
u2 = np.array([-5, 2, 1]).reshape((3,1))
u3 = np.array([-1, -3, 7]).reshape((3,1))

#affichons les différents vecteurs
u1, u2, u3

(array([1, 2, 3]),
 array([[-5],
        [ 2],
        [ 1]]),
 array([[-1],
        [-3],
        [ 7]]))

2. Calculons u<sub>1</sub> + u<sub>2</sub>,u<sub>1</sub> + 3u<sub>2</sub> − 5u<sub>3</sub>,u<sub>3</sub>/5

In [2]:
print("Le résultat de l'opération u_(1) + u_(2) est : \n {}".format(u1 + u2))
print("Le résultat de l'opération u_(1) + 3u_(2) - 5u_(3) est : \n {}".format(u1 + 3*u2 - 5*u3))
print("Le résultat de l'opération u_(3)/5 est : \n {}".format(u3 / 5))

Le résultat de l'opération u_(1) + u_(2) est : 
 [[-4 -3 -2]
 [ 3  4  5]
 [ 2  3  4]]
Le résultat de l'opération u_(1) + 3u_(2) - 5u_(3) est : 
 [[ -9  -8  -7]
 [ 22  23  24]
 [-31 -30 -29]]
Le résultat de l'opération u_(3)/5 est : 
 [[-0.2]
 [-0.6]
 [ 1.4]]


3. Calculons le produit des compansantes des vecteur u<sub>1</sub> et u<sub>2</sub>, terme à terme.

In [3]:
u1 * u2

array([[ -5, -10, -15],
       [  2,   4,   6],
       [  1,   2,   3]])

4. Calculons les produits u<sup>T</sup><sub>1</sub> u<sub>2</sub> et u<sub>1</sub> u<sup>T</sup><sub>2</sub>.

In [4]:
u1T = u1.reshape(3,1)
u2T = u2.reshape(3,1)
print("Le produit uT1*u2 donne : \n {}".format(u1T * u2))
print("Le produit u1*uT2 donne : \n {}".format(u1 * u2T))

Le produit uT1*u2 donne : 
 [[-5]
 [ 4]
 [ 3]]
Le produit u1*uT2 donne : 
 [[ -5 -10 -15]
 [  2   4   6]
 [  1   2   3]]


5. Créons par concaténation la matrice :

In [5]:
np.concatenate((u1T, u2, u3)).reshape((3, 3)).T

array([[ 1, -5, -1],
       [ 2,  2, -3],
       [ 3,  1,  7]])

In [6]:
np.hstack((u1.reshape((3, 1)), u2, u3))

array([[ 1, -5, -1],
       [ 2,  2, -3],
       [ 3,  1,  7]])

#### Exercice 2 - Opérations matricielles


Soit le vecteur 
$$
u = 
\begin{bmatrix}
1 \\
2 \\
-5 \\
2 \\
-1 \\
-3
\end{bmatrix}
$$

1. Calculer la somme des composantes du vecteur u sans utiliser la fonction <code>sum</code> de <code>numpy</code>
2. Calculer le produit des composantes du vecteur u sans utiliser la fonction <code>prod</code> de <code>numpy</code>

In [7]:
u = np.array([1, 2, -5, 2, -1, -3]).reshape((6, 1))
somme = 0
produit = 1
for i in u :
    somme += i
    produit *= i
print("1. La somme des composantes du vecteur u est : {}".format(somme))
print("2. Le produit des composantes du vecteur u est : {}".format(produit))

1. La somme des composantes du vecteur u est : [-4]
2. Le produit des composantes du vecteur u est : [-60]


#### Exercice 3

Considérons le vecteur suivant : 
$$
x = 
\begin{bmatrix}
1 & 2 & 3 & 4 & 5
\end{bmatrix}
$$

1. Créer ce vecteur à l’aide d’un tableau que l’on appellera x.
2. Afficher le type de x puis sa longueur.
3. Extraire le premier élément, puis en faire de même avec le dernier.
4. Extraire les trois premiers éléments et les stocker dans un vecteur que l’on nommera a.
5. Extraire les 1er, 2e et 5e éléments du vecteur (attention aux positions) ; les stocker dans un vecteur que l’on nommera b.
6. Additionner le nombre 10 au vecteur x, puis multiplier le résultat par 2.
7. Effectuer l’addition de a et b, commenter le résultat.
8. Effectuer l’addition suivante : x+a ; commenter le résultat, puis regarder le résultat de a+x.
9. Multiplier le vecteur par le scalaire c que l’on fixera à 2.
10. Effectuer la multiplication de a et b ; commenter le résultat.
11. Effectier la multiplication suivante : x*a ; commenter le résultats.
12. Récupérer les positions des multiples de 2 et les stocker dans un vecteur que l’on nommera ind, piuis conserver uniquement les multiples de 2 de x dans un vecteur que l’on nommera mult_2.
13. Afficher les éléments de x qui sont multiples de 3 et multiples de 2.
14. Afficher les éléments de x qui sont multiples de 3 ou multiples de 2.
15. Calculer la somme des éléments de x.
16. Remplacer le premier élément de x par un 4.
17. Remplacer le premier élément de x par la valeur NaN, puis calculer la somme des éléments de x. 
18. Supprimer le vecteur x.

1. Créer ce vecteur à l’aide d’un tableau que l’on appellera x.

In [8]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

2. Afficher le type de x puis sa longueur.

In [9]:
print("Le type de x est {} et la longueur de x est {}".format(type(x),len(x)))

Le type de x est <class 'numpy.ndarray'> et la longueur de x est 5


3. Extraire le premier élément, puis en faire de même avec le dernier.

In [10]:
#Extraction du premier élément
print("Le premier élément est {}".format(x[0]))
#Extraction du dernier élément
print("Le dernier élément est {}".format(x[4]))

Le premier élément est 1
Le dernier élément est 5


4. Extraire les trois premiers éléments et les stocker dans un vecteur que l’on nommera a.

In [11]:
a = x[0:3]
a

array([1, 2, 3])

5. Extraire les 1er, 2e et 5e éléments du vecteur (attention aux positions) ; les stocker dans un vecteur que l’on nommera b.

In [12]:
indice = [0, 1, 4]
b = x[indice]
b

array([1, 2, 5])

6. Additionner le nombre 10 au vecteur x, puis multiplier le résultat par 2.

In [13]:
(10 + x) * 2

array([22, 24, 26, 28, 30])

7. Effectuer l’addition de a et b, commenter le résultat.

In [14]:
a + b

array([2, 4, 8])

8. Effectuer l’addition suivante : x+a ; commenter le résultat, puis regarder le résultat de a+x.

In [15]:
try:
    somme_x_a = x + a
    print("Addition de x et a :", somme_x_a)
except ValueError as e:
    print("Erreur dans x + a :", e)

try:
    somme_a_x = a + x
    print("Addition de a et x :", somme_a_x)
except ValueError as e:
    print("Erreur dans a + x :", e)

Erreur dans x + a : operands could not be broadcast together with shapes (5,) (3,) 
Erreur dans a + x : operands could not be broadcast together with shapes (3,) (5,) 


9. Multiplier le vecteur par le scalaire c que l’on fixera à 2.

In [16]:
c = 2
x*c

array([ 2,  4,  6,  8, 10])

10. Effectuer la multiplication de a et b ; commenter le résultat.

In [17]:
a * b

array([ 1,  4, 15])

11. Effectier la multiplication suivante : x*a ; commenter le résultats.

In [18]:
try:
    prod_x_a = x * a
    print("Multiplication de x et a :", prod_x_a)
except ValueError as e:
    print("Erreur dans x * a :", e)

Erreur dans x * a : operands could not be broadcast together with shapes (5,) (3,) 


12. Récupérer les positions des multiples de 2 et les stocker dans un vecteur que l’on nommera ind, piuis conserver uniquement les multiples de 2 de x dans un vecteur que l’on nommera mult_2.

In [19]:
ind = np.where(x%2==0)
#stocker les multiples de 2 dans un vecteur (mult_2)
mult_2 = x[ind]
mult_2

array([2, 4])

13. Afficher les éléments de x qui sont multiples de 3 et multiples de 2.

In [20]:
multiples_3_et_2 = x[(x % 3 == 0) & (x % 2 == 0)]
print("Éléments multiples de 3 et 2 :", multiples_3_et_2)

Éléments multiples de 3 et 2 : []


14. Afficher les éléments de x qui sont multiples de 3 ou multiples de 2.

In [21]:
multiples_3_ou_2 = x[(x % 3 == 0) | (x % 2 == 0)]
print("Éléments multiples de 3 ou 2 :", multiples_3_ou_2)

Éléments multiples de 3 ou 2 : [2 3 4]


15. Calculer la somme des éléments de x.

In [22]:
x.sum()

15

16. Remplacer le premier élément de x par un 4.

In [23]:
x[0] = 4
x

array([4, 2, 3, 4, 5])

17. Remplacer le premier élément de x par la valeur NaN, puis calculer la somme des éléments de x.

In [30]:
x[0] = np.nan
somme_x_nan = np.nansum(x)

ValueError: cannot convert float NaN to integer

18. Supprimer le vecteur x.

In [ ]:
del x
try:
    print(x)
except NameError:
    print("Le vecteur x a été supprimé.")

#### Exercice 4

1. Créer la matrice suivante : 
$$ A = \begin{bmatrix} -3 & 5 & 6 \\ -1 & 2 & 2 \\ 1 & -1 & -1 \end{bmatrix} $$
2. Afficher la dimension de A, son nombre de colonnes, son nombre de lignes et sa longueur.
3. Extraire la seconde colonne de A, puis la première ligne. 4.Extraire l’élément en troisième position à la première ligne.
4. Extraire la sous-matrice de dimension du coin inférieur de A, c’est-à-dire $$ \begin{bmatrix} 2 & 2 \\ -1 & -1 \end{bmatrix} $$
5. Calculer la somme des colonnes puis des lignes de A.
6. Afficher la diagonale de A.
7. Rajouter le vecteur $$ \begin{bmatrix} 1 & 2 & 3\end{bmatrix}^\top $$ à droite de la matrice A et stocker le résultat dans un objet appelé B.
8. Retirer le quatrième vecteur de B.
9. Retirer la première et la troisième ligne de B.
10. Ajouter le scalaire 10 à A.
11. Ajouter le vecteur $$ \begin{bmatrix} 1 & 2 & 3\end{bmatrix}^\top $$ à A.
12. Ajouter la matrice identité \(I_3\) à A.
13. Diviser tous les éléments de la matrice A par 2.
14. Multiplier la matrice A par le vecteur ligne $$ \begin{bmatrix} 1 & 2 & 3\end{bmatrix}^\top $$
15. Afficher la transposée de A.
16. Effectuer le produit avec transposition $$ A^\top A $$

1. Créons la matrice : 
$$ A = \begin{bmatrix} -3 & 5 & 6 \\ -1 & 2 & 2 \\ 1 & -1 & -1 \end{bmatrix} $$

In [ ]:
A=np.array([[-3,5,6],[-1,2,2],[1,-1,-1]])
print(A)

2. Afficher la dimension de A, son nombre de colonnes, son nombre de lignes et sa longueur

In [ ]:
print("Dimension de A (lignes, colonnes) :", A.shape)
print("Nombre de lignes de A :", A.shape[0])
print("Nombre de colonnes de A :", A.shape[1])
print("Longueur de A (nombre total d'éléments) :", A.size)

3. Extraire la seconde colonne de A, puis la première ligne. 4.Extraire l’élément en troisième position à la première ligne.

In [ ]:
# Extraire la seconde colonne de A
seconde_colonne = A[:, 1]
print("Seconde colonne de A :", seconde_colonne)
# Extraire la première ligne de A
prem_ligne = A[0, :]
print("Première ligne de A :", prem_ligne)
# Extraire l'élément en troisième position à la première ligne
element_3eme_position = A[0, 2]
print("Élément en troisième position à la première ligne :", element_3eme_position)

4. Extraire la sous-matrice de dimension du coin inférieur de A, c’est-à-dire $$ \begin{bmatrix} 2 & 2 \\ -1 & -1 \end{bmatrix} $$

In [ ]:
sous_matrice_coin_inferieur = A[1:, 1:]
print("Sous-matrice du coin inférieur de A :")
print(sous_matrice_coin_inferieur)

5. Calculer la somme des colonnes puis des lignes de A.

In [ ]:
# Calculer la somme des colonnes
somme_colonnes = np.sum(A, axis=0)
print("Somme des colonnes de A :")
print(somme_colonnes)

# Calculer la somme des lignes
somme_lignes = np.sum(A, axis=1)
print("Somme des lignes de A :")
print(somme_lignes)


6. Afficher la diagonale de A.

In [ ]:
diagonale = np.diagonal(A)
print("Diagonale de A :")
print(diagonale)

7. Rajouter le vecteur $$ \begin{bmatrix} 1 & 2 & 3\end{bmatrix}^\top $$ à droite de la matrice A et stocker le résultat dans un objet appelé B.

In [ ]:
# Créer le vecteur colonne [1, 2, 3]^T (de taille 3x1)
vecteur = np.array([[1], [2], [3]])
print(vecteur)
# Ajouter le vecteur à droite de la matrice A
B = np.hstack((A, vecteur))
print("Matrice A après ajout du vecteur à droite :")
print(B)

8. Retirer le quatrième vecteur de B.

In [ ]:
B_sans_quatrieme_colonne = np.delete(B, 3, axis=1)
print("Matrice B sans le quatrième vecteur (colonne) :")
print(B_sans_quatrieme_colonne)

9. Retirer la première et la troisième ligne de B.

In [ ]:
B_sans_premiere_troisieme_ligne = np.delete(B, [0, 2], axis=0)
print("Matrice B sans la première et la troisième ligne :")
print(B_sans_premiere_troisieme_ligne)

10. Ajouter le scalaire 10 à A.

In [ ]:
A_avec_10 = A + 10
print("Matrice A après ajout de 10 à chaque élément :")
print(A_avec_10)

11. Ajouter le vecteur $$ \begin{bmatrix} 1 & 2 & 3\end{bmatrix}^\top $$ à A.

In [ ]:
vecteur = np.array([[1], [2], [3]])
A_v = np.hstack((A, vecteur))
print("Matrice A après ajout du vecteur colonne :")
print(A_v)

12. Ajouter la matrice identité \(I_3\) à A.

In [ ]:
I_3 = np.eye(3)
A_I = A + I_3
print("\nMatrice A après ajout de l'identité I_3 :")
print(A_I)

13. Diviser tous les éléments de la matrice A par 2.

In [ ]:
A_div = A / 2
print("\nMatrice A divisée par 2 :")
print(A_div)

14. Multiplier la matrice A par le vecteur ligne $$ \begin{bmatrix} 1 & 2 & 3\end{bmatrix}^\top $$

In [ ]:
vecteur_ligne = np.array([1, 2, 3])
A_mult_v = np.dot(A, vecteur_ligne)
print("\nMatrice A multipliée par le vecteur ligne :")
print(A_mult_v)

15. Afficher la transposée de A.

In [ ]:
A_t = A.T
print("\nTransposée de la matrice A :")
print(A_t)

16. Effectuer le produit avec transposition $$ A^\top A $$

In [ ]:
prod_trans = np.dot(A, A.T)
print("\nProduit de A avec sa transposée (A * A^T) :")
print(prod_trans)